### ISSUE TITLE
unlimited limit

### ISSUE THREAD

**Issue by myasonik** [pkbigmarsh/Gen-Con-Buddy-API#11]
I want to fetch all events so I set the limit to 100000 but that causes a 500 (smaller numbers work fine, not sure what the max is)

https://pacific-plains-10689-8ac0e606559a.herokuapp.com/api/events/search?filter=test&limit=100000

Maybe we should support something like "all" instead of me setting just ridiculously large numbers?

**Comment by pkbigmarsh** [comment]
So that doesn't work with OpenSearch. There is no ability to return all results. The max result size you can use is 10k. So there's no real difference between creating an `all` filter parameter and you providing 10k as the limit. However, I'm not sure if that's worth it for performance... You should probably be creating pages and not fetching 10k at a time.

**Comment by myasonik** [comment]
Fiiiiinnnnneeee
